import{a as S,S as w,i as n}from"./assets/vendor-DfezCyqK.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const q="51382784-75992f1b54a5aaf18615b0258",P="https://pixabay.com/api/";async function f(o,e=1){return(await S.get(P,{params:{key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}})).data}const p=document.querySelector(".gallery"),m=document.querySelector(".loader"),h=document.querySelector(".load-btn");let $=new w(".gallery a",{captionsData:"alt",captionDelay:250});function R({webformatURL:o,largeImageURL:e,tags:s,likes:a,views:t,comments:r,downloads:i}){return`
    <li class="gallery-item">
      <a class="gallery-link" href="${e}">
        <img class="gallery-image" src="${o}" alt="${s}" />
      </a>
      <div class="info">
        <p class="info-label">Likes <span class="info-value">${a}</span></p>
        <p class="info-label">Views <span class="info-value">${t}</span></p>
        <p class="info-label">Comments <span class="info-value">${r}</span></p>
        <p class="info-label">Downloads <span class="info-value">${i}</span></p>
      </div>
    </li>
  `}function g(o){const e=o.map(R).join("");p.insertAdjacentHTML("beforeend",e),$.refresh()}function B(){p.innerHTML=""}function y(){m.classList.remove("hidden")}function L(){m.classList.add("hidden")}function b(){h.classList.remove("hidden")}function u(){h.classList.add("hidden")}const v=document.querySelector(".form"),A=document.querySelector(".load-btn");let c="",l=1,d=0;const E=15;v.addEventListener("submit",M);A.addEventListener("click",x);async function M(o){if(o.preventDefault(),c=o.currentTarget.elements["search-text"].value.trim(),!c){n.error({title:"Error",message:"Please enter something in the search field.",position:"topRight"});return}l=1,B(),u(),y();try{const e=await f(c,l);if(d=e.totalHits,e.hits.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(e.hits),d>E?b():n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(e){n.error({title:"Error",message:`An error occurred: ${e.message}`,position:"topRight"})}finally{L(),v.reset()}}async function x(){l+=1,u(),y();try{const o=await f(c,l);g(o.hits);const e=document.querySelector(".gallery-item");if(e){const a=e.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}const s=Math.ceil(d/E);l>=s?(u(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch(o){n.error({title:"Error",message:`An error occurred: ${o.message}`,position:"topRight"})}finally{L()}}
//# sourceMappingURL=index.js.map
